<a href="https://colab.research.google.com/github/Anusarakh/DPDM2021/blob/main/test_musictable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
text_list = ['''ได้เจอครั้งสุดท้ายตอนที่ดูรูปถ่ายและเมื่อหลับตาครั้งใดยังเห็นเธอ  กอดเธอในฝัน ฉันน้ำตาล้นเอ่อ สุขเพียงได้เจอในจินตนาการ 
แม้เพลงนี้เธอไม่ได้ฟังทุกทุกคำที่เคยบอกไว้งดงามแม้ยิ่งห้ามใจฉันจำได้เสมอ ที่เธอเคยบอกฉัน อย่าร้องไห้อยู่ให้ได้ถ้าเธอไม่อยู่โปรดรับรู้เธอยังอยู่ในใจ ที่เธอเคยบอกฉัน 
อย่าร้องไห้อยากขอโทษที่ทำไม่ได้ที่วาดไว้ด้วยกันจากนี้ฉันต้องฝันคนเดียวบรรจงวาดฝันให้งดงามเหมือนเก่าสุขเกิดเพียงเราถ่วงทุกข์ให้จมดิ่งเพียงแค่ตื่นนั้นก็เลือนลางทุกสิ่ง
เพราะความเป็นจริงนั้นมีบางสิ่งที่จากไปแม้เธอนั้นไม่หวนคืนกลับใจซึมซับไปด้วยความหมายเหมือนว่ามีเธอข้างกาย ยังจำได้เสมอที่เธอเคยบอกฉัน 
อย่าร้องไห้อยู่ให้ได้ถ้าเธอไม่อยู่โปรดรับรู้เธอยังอยู่ในใจที่เธอเคยบอกฉัน อย่าร้องไห้อยากขอโทษ ที่ทำไม่ได้ที่วาดไว้ด้วยกันแต่ว่าเธอไม่ได้มาส่งถึงฝั่งฝันไกลนานแค่ไหนยังคงวาดไว้ว่าเรามีกัน ที่เธอเคยบอกฉัน 
อย่าร้องไห้อยู่ให้ได้ถ้าเธอไม่อยู่โปรดรับรู้เธอยังอยู่ในใจที่เธอเคยบอกฉัน อย่าร้องไห้อยากขอโทษที่ทำไม่ได้ที่วาดไว้ด้วยกันจากนี้ฉันต้องฝันคนเดียว''',
             
            '''WholeNote  HalfNote QuarterNot EighthNote''']

In [2]:
import re
import string

def clean_msg(msg):
    
    
    # ลบ text ที่อยู่ในวงเล็บ <> ทั้งหมด
    msg = re.sub(r'<.*?>','', msg)
    
    # ลบ hashtag
    msg = re.sub(r'#','',msg)
    
    # ลบ เครื่องหมายคำพูด (punctuation)
    for c in string.punctuation:
        msg = re.sub(r'\{}'.format(c),'',msg)
    
    # ลบ separator เช่น \n \t
    msg = ' '.join(msg.split())
    
    return msg

In [3]:
print('original text:\n',text_list[0])
print('clean text:\n',clean_msg(text_list[0]))

original text:
 ได้เจอครั้งสุดท้ายตอนที่ดูรูปถ่ายและเมื่อหลับตาครั้งใดยังเห็นเธอ  กอดเธอในฝัน ฉันน้ำตาล้นเอ่อ สุขเพียงได้เจอในจินตนาการ 
แม้เพลงนี้เธอไม่ได้ฟังทุกทุกคำที่เคยบอกไว้งดงามแม้ยิ่งห้ามใจฉันจำได้เสมอ ที่เธอเคยบอกฉัน อย่าร้องไห้อยู่ให้ได้ถ้าเธอไม่อยู่โปรดรับรู้เธอยังอยู่ในใจ ที่เธอเคยบอกฉัน 
อย่าร้องไห้อยากขอโทษที่ทำไม่ได้ที่วาดไว้ด้วยกันจากนี้ฉันต้องฝันคนเดียวบรรจงวาดฝันให้งดงามเหมือนเก่าสุขเกิดเพียงเราถ่วงทุกข์ให้จมดิ่งเพียงแค่ตื่นนั้นก็เลือนลางทุกสิ่ง
เพราะความเป็นจริงนั้นมีบางสิ่งที่จากไปแม้เธอนั้นไม่หวนคืนกลับใจซึมซับไปด้วยความหมายเหมือนว่ามีเธอข้างกาย ยังจำได้เสมอที่เธอเคยบอกฉัน 
อย่าร้องไห้อยู่ให้ได้ถ้าเธอไม่อยู่โปรดรับรู้เธอยังอยู่ในใจที่เธอเคยบอกฉัน อย่าร้องไห้อยากขอโทษ ที่ทำไม่ได้ที่วาดไว้ด้วยกันแต่ว่าเธอไม่ได้มาส่งถึงฝั่งฝันไกลนานแค่ไหนยังคงวาดไว้ว่าเรามีกัน ที่เธอเคยบอกฉัน 
อย่าร้องไห้อยู่ให้ได้ถ้าเธอไม่อยู่โปรดรับรู้เธอยังอยู่ในใจที่เธอเคยบอกฉัน อย่าร้องไห้อยากขอโทษที่ทำไม่ได้ที่วาดไว้ด้วยกันจากนี้ฉันต้องฝันคนเดียว
clean text:
 ได้เจอครั้งสุดท้ายตอนที่ดูรูปถ่ายและ

In [4]:
print('original text:\n',text_list[1])
print('clean text:\n',clean_msg(text_list[1]))

original text:
 WholeNote  HalfNote QuarterNot EighthNote
clean text:
 WholeNote HalfNote QuarterNot EighthNote


In [5]:
clean_text = [clean_msg(txt) for txt in text_list]

# Step 2: Tokenize  ตัดคำ

In [13]:
!pip install pythainlp
!pip install stop_words

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [14]:
import pythainlp
from pythainlp import word_tokenize
# from pythainlp.corpus import stopwords
# from nltk.corpus import stopwords
# import stop_words #as stopwords
from pythainlp.corpus import wordnet
from nltk.stem.porter import PorterStemmer
from nltk.corpus import words
from stop_words import get_stop_words

In [15]:
pythainlp.corpus.common.thai_stopwords()

frozenset({'ขณะใดๆ',
           'บ่อยๆ',
           'เป็นเพื่อ',
           'บน',
           'ที่',
           'ถ้า',
           'มัก',
           'ตลอดกาลนาน',
           'พึ่ง',
           'ถึงแก่',
           'ตลอดไป',
           'ให้ไป',
           'พร้อมทั้ง',
           'มุ่งเน้น',
           'วันใด',
           'เช่น',
           'ทันที',
           'อย่างหนึ่ง',
           'นี้เอง',
           'ได้แต่',
           'สิ่งนี้',
           'นู่น',
           'ยกให้',
           'พวกกู',
           'เพราะว่า',
           'เมื่อนั้น',
           'จนตลอด',
           'ก่อนๆ',
           'บ่อยกว่า',
           'หน',
           'จ้ะ',
           'แต่ไร',
           'เช่นไร',
           'แสดงว่า',
           'เป็นด้วย',
           'ด้วยเพราะ',
           'เท่ากับ',
           'เสร็จสมบูรณ์',
           'ไว้',
           'พวกโน้น',
           'ซะ',
           'ด้วยกัน',
           'เห็นแก่',
           'รึ',
           'แสดง',
           'สำคัญ',
           'อดีต',
           'อยู่',
    

In [19]:
import nltk
nltk.download('words')
nltk.download('omw-1.4')
th_stop = tuple(pythainlp.corpus.common.thai_stopwords())
# th_stop = tuple(stopwords.words('thai'))
en_stop = tuple(get_stop_words('en'))
p_stemmer = PorterStemmer()

[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


In [21]:
def split_word(text):
            
    
    tokens = word_tokenize(text,engine='newmm')
    
    # Remove stop words ภาษาไทย และภาษาอังกฤษ
    tokens = [i for i in tokens if not i in th_stop and not i in en_stop]
    
    # หารากศัพท์ภาษาไทย และภาษาอังกฤษ
    # English
    tokens = [p_stemmer.stem(i) for i in tokens]
    
    # Thai
    tokens_temp=[]
    for i in tokens:
        w_syn = wordnet.synsets(i)
        if (len(w_syn)>0) and (len(w_syn[0].lemma_names('tha'))>0):
            tokens_temp.append(w_syn[0].lemma_names('tha')[0])
        else:
            tokens_temp.append(i)
    
    tokens = tokens_temp
    
    # ลบตัวเลข
    tokens = [i for i in tokens if not i.isnumeric()]
    
    # ลบช่องว่าง
    tokens = [i for i in tokens if not ' ' in i]

    return tokens

In [22]:
print('tokenized text:\n',split_word(clean_msg(text_list[0])))
print('tokenized text:\n',split_word(clean_msg(text_list[1])))

tokenized text:
 ['ประจันหน้า', 'ครั้งสุดท้าย', 'ตอนที่', 'ดู', 'ภาพ', 'หลับตา', 'ใด', 'กอด', 'ทรงพระสุบิน', 'น้ำตา', 'ล้น', 'เอ่อ', 'สุข', 'ประจันหน้า', 'ในจินตนาการ', 'เพลง', 'ฟัง', 'งดงาม', 'ห้ามใจ', 'จำได้', 'เจ๊า', 'อย่า', 'ทรงกันแสง', 'ให้ได้', 'ชอบ', 'รับรู้', 'ยังอยู่', 'จิต', 'อย่า', 'ทรงกันแสง', 'ขอโทษ', 'ทำ', 'วาด', 'ทรงพระสุบิน', 'คนเดียว', 'บรรจง', 'วาด', 'ทรงพระสุบิน', 'งดงาม', 'เปรียบเสมือน', 'ก่อน', 'สุข', 'ถ่วง', 'ทุกข์', 'จมดิ่ง', 'ตื่น', 'เลือนลาง', 'ความเป็นจริง', 'บางสิ่ง', 'จากไป', 'หวนคืน', 'กลับใจ', 'ซึมซับ', 'ความหมาย', 'เหมือนว่า', 'กาย', 'จำได้', 'เจ๊า', 'อย่า', 'ทรงกันแสง', 'ให้ได้', 'ชอบ', 'รับรู้', 'ยังอยู่', 'จิต', 'อย่า', 'ทรงกันแสง', 'ขอโทษ', 'ทำ', 'วาด', 'ฝั่ง', 'ทรงพระสุบิน', 'วาด', 'อย่า', 'ทรงกันแสง', 'ให้ได้', 'ชอบ', 'รับรู้', 'ยังอยู่', 'จิต', 'อย่า', 'ทรงกันแสง', 'ขอโทษ', 'ทำ', 'วาด', 'ทรงพระสุบิน', 'คนเดียว']
tokenized text:
 ['wholenot', 'halfnot', 'quarternot', 'eighthnot']


In [23]:
tokens_list = [split_word(txt) for txt in clean_text]

In [24]:
tokens_list

[['ประจันหน้า',
  'ครั้งสุดท้าย',
  'ตอนที่',
  'ดู',
  'ภาพ',
  'หลับตา',
  'ใด',
  'กอด',
  'ทรงพระสุบิน',
  'น้ำตา',
  'ล้น',
  'เอ่อ',
  'สุข',
  'ประจันหน้า',
  'ในจินตนาการ',
  'เพลง',
  'ฟัง',
  'งดงาม',
  'ห้ามใจ',
  'จำได้',
  'เจ๊า',
  'อย่า',
  'ทรงกันแสง',
  'ให้ได้',
  'ชอบ',
  'รับรู้',
  'ยังอยู่',
  'จิต',
  'อย่า',
  'ทรงกันแสง',
  'ขอโทษ',
  'ทำ',
  'วาด',
  'ทรงพระสุบิน',
  'คนเดียว',
  'บรรจง',
  'วาด',
  'ทรงพระสุบิน',
  'งดงาม',
  'เปรียบเสมือน',
  'ก่อน',
  'สุข',
  'ถ่วง',
  'ทุกข์',
  'จมดิ่ง',
  'ตื่น',
  'เลือนลาง',
  'ความเป็นจริง',
  'บางสิ่ง',
  'จากไป',
  'หวนคืน',
  'กลับใจ',
  'ซึมซับ',
  'ความหมาย',
  'เหมือนว่า',
  'กาย',
  'จำได้',
  'เจ๊า',
  'อย่า',
  'ทรงกันแสง',
  'ให้ได้',
  'ชอบ',
  'รับรู้',
  'ยังอยู่',
  'จิต',
  'อย่า',
  'ทรงกันแสง',
  'ขอโทษ',
  'ทำ',
  'วาด',
  'ฝั่ง',
  'ทรงพระสุบิน',
  'วาด',
  'อย่า',
  'ทรงกันแสง',
  'ให้ได้',
  'ชอบ',
  'รับรู้',
  'ยังอยู่',
  'จิต',
  'อย่า',
  'ทรงกันแสง',
  'ขอโทษ',
  'ทำ',
  'วาด',
  'ทรงพระสุบ

#Step 3 + 4a: Bag of words + count word

In [25]:
from sklearn.feature_extraction.text import CountVectorizer
tokens_list_j = [','.join(tkn) for tkn in tokens_list]
cvec = CountVectorizer(analyzer=lambda x:x.split(','))
c_feat = cvec.fit_transform(tokens_list_j)

In [ ]:
from pythainlp.corpus import thai_stopwords

In [26]:
cvec.vocabulary_

{'ประจันหน้า': 31,
 'ครั้งสุดท้าย': 10,
 'ตอนที่': 21,
 'ดู': 20,
 'ภาพ': 34,
 'หลับตา': 40,
 'ใด': 50,
 'กอด': 5,
 'ทรงพระสุบิน': 25,
 'น้ำตา': 28,
 'ล้น': 37,
 'เอ่อ': 49,
 'สุข': 39,
 'ในจินตนาการ': 51,
 'เพลง': 46,
 'ฟัง': 33,
 'งดงาม': 13,
 'ห้ามใจ': 42,
 'จำได้': 16,
 'เจ๊า': 44,
 'อย่า': 43,
 'ทรงกันแสง': 24,
 'ให้ได้': 52,
 'ชอบ': 18,
 'รับรู้': 36,
 'ยังอยู่': 35,
 'จิต': 17,
 'ขอโทษ': 8,
 'ทำ': 26,
 'วาด': 38,
 'คนเดียว': 9,
 'บรรจง': 29,
 'เปรียบเสมือน': 45,
 'ก่อน': 7,
 'ถ่วง': 23,
 'ทุกข์': 27,
 'จมดิ่ง': 14,
 'ตื่น': 22,
 'เลือนลาง': 47,
 'ความเป็นจริง': 12,
 'บางสิ่ง': 30,
 'จากไป': 15,
 'หวนคืน': 41,
 'กลับใจ': 4,
 'ซึมซับ': 19,
 'ความหมาย': 11,
 'เหมือนว่า': 48,
 'กาย': 6,
 'ฝั่ง': 32,
 'wholenot': 3,
 'halfnot': 1,
 'quarternot': 2,
 'eighthnot': 0}

In [34]:
c_feat[:,:].todense()

matrix([[0, 0, 0, 0, 1, 1, 1, 1, 3, 2, 1, 1, 1, 2, 1, 1, 2, 3, 3, 1, 1,
         1, 1, 1, 6, 5, 3, 1, 1, 1, 1, 2, 1, 1, 1, 3, 3, 1, 5, 2, 1, 1,
         1, 6, 2, 1, 1, 1, 1, 1, 1, 1, 3],
        [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

#Step 3 + 4b: Bag of words + tf-idf

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer
tvec = TfidfVectorizer(analyzer=lambda x:x.split(','),)
t_feat = tvec.fit_transform(tokens_list_j)

In [32]:
t_feat[:,:].todense()

matrix([[0.        , 0.        , 0.        , 0.        , 0.06441566,
         0.06441566, 0.06441566, 0.06441566, 0.19324699, 0.12883133,
         0.06441566, 0.06441566, 0.06441566, 0.12883133, 0.06441566,
         0.06441566, 0.12883133, 0.19324699, 0.19324699, 0.06441566,
         0.06441566, 0.06441566, 0.06441566, 0.06441566, 0.38649398,
         0.32207831, 0.19324699, 0.06441566, 0.06441566, 0.06441566,
         0.06441566, 0.12883133, 0.06441566, 0.06441566, 0.06441566,
         0.19324699, 0.19324699, 0.06441566, 0.32207831, 0.12883133,
         0.06441566, 0.06441566, 0.06441566, 0.38649398, 0.12883133,
         0.06441566, 0.06441566, 0.06441566, 0.06441566, 0.06441566,
         0.06441566, 0.06441566, 0.19324699],
        [0.5       , 0.5       , 0.5       , 0.5       , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 

In [30]:
print(len(tvec.idf_),len(tvec.vocabulary_))

53 53


In [33]:
c_feat[:,:].todense()

matrix([[0, 0, 0, 0, 1, 1, 1, 1, 3, 2, 1, 1, 1, 2, 1, 1, 2, 3, 3, 1, 1,
         1, 1, 1, 6, 5, 3, 1, 1, 1, 1, 2, 1, 1, 1, 3, 3, 1, 5, 2, 1, 1,
         1, 6, 2, 1, 1, 1, 1, 1, 1, 1, 3],
        [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

#Test data ในตาราง

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive # เชื่อม google drive
drive.mount('/content/drive')

In [ ]:
import os
path = '/content/drive/My Drive/Thesis' # เรียกข้อมูลจาก Drive 

In [ ]:
music_data = pd.read_csv(os.path.join(path,'lyrics data.csv'))
music_data